export const colors = {
  comicBorderColor: '#17172A',
  comicBorderWidth: 2,
  comicShadowOffset: 4,
  paper: '#FFFFFF',
  paperInkWash: '#F7F5FF',
  paperLavender: '#F1F3FF',
  comicShadowTint: '#17172A',
  comicBlueWash: '#E0F2FE',
  comicYellowWash: '#FFF3B8',
  comicPinkWash: '#FCE7F3',
  lavenderBackground: '#F7F5FF',
  softLavenderPanel: '#F1F3FF',
  primaryPurple: '#5B45F6',
  deepPurple: '#4221DE',
  yellowCta: '#FFD600',
  cyanAccent: '#00E5FF',
  errorCoral: '#FF5252',
  successGreen: '#A4FF00',
  articleDerBlue: '#0EA5E9',
  articleDiePink: '#EC4899',
  articleDasAmber: '#F59E0B',
  deepViolet: '#17172A',
  royalPurple: '#5B45F6',
  lavender: '#E9E6FF',
  yellow: '#FFD600',
  green: '#2DBE73',
  red: '#FF5252',
  white: '#FFFFFF',
  ink: '#17172A',
  muted: '#5E5B73',
  border: '#D8D2F5',
  surface: '#F7F5FF',
  surfaceStrong: '#F1F3FF',
  surfaceWarm: '#FFFDF8',
  card: '#FFFFFF',
  cardMuted: '#F1EEFF',
  overlay: 'rgba(23,23,42,0.48)',
  gradientStart: '#5B45F6',
  gradientEnd: '#17172A',
  articleDer: '#0EA5E9',
  articleDie: '#EC4899',
  articleDas: '#F59E0B',
};

export const articleColors = {
  der: colors.articleDer,
  die: colors.articleDie,
  das: colors.articleDas,
};

export const articleLightColors = {
  der: '#D8EFFF',
  die: '#FFE1F0',
  das: '#FEF3C7',
};
