export const colors = {
  comicBorderColor: '#1A1A2E',
  comicBorderWidth: 2,
  comicShadowOffset: 4,
  paper: '#FFFDF7',
  paperInkWash: '#F7F1FF',
  paperLavender: '#F6F3FF',
  comicShadowTint: '#141225',
  comicBlueWash: '#E7F0FF',
  comicYellowWash: '#FFF3B8',
  comicPinkWash: '#FFE4EF',
  lavenderBackground: '#FAF9FF',
  softLavenderPanel: '#F1F3FF',
  primaryPurple: '#5B45F6',
  deepPurple: '#4221DE',
  yellowCta: '#FFD600',
  cyanAccent: '#00E5FF',
  errorCoral: '#FF5252',
  successGreen: '#A4FF00',
  articleDerBlue: '#4B8DFF',
  articleDiePink: '#EF5B9C',
  articleDasAmber: '#FFB000',
  deepViolet: '#1A1A2E',
  royalPurple: '#5B45F6',
  lavender: '#E9E6FF',
  yellow: '#FFD600',
  green: '#2DBE73',
  red: '#FF5252',
  white: '#FFFFFF',
  ink: '#151322',
  muted: '#57516E',
  border: '#DED8FF',
  surface: '#FAF9FF',
  surfaceStrong: '#F1F3FF',
  surfaceWarm: '#FFFDF8',
  card: '#FFFFFF',
  cardMuted: '#F1F3FF',
  overlay: 'rgba(26,26,46,0.42)',
  gradientStart: '#7C5CFF',
  gradientEnd: '#4221DE',
  articleDer: '#4B8DFF',
  articleDie: '#EF5B9C',
  articleDas: '#FFB000',
};

export const articleColors = {
  der: colors.articleDer,
  die: colors.articleDie,
  das: colors.articleDas,
};

export const articleLightColors = {
  der: '#D8E8FF',
  die: '#FFE0EA',
  das: '#FFF1C7',
};
